export type EntryType = 'Innhopp' | 'Transport' | 'Ground Crew' | 'Accommodation' | 'Other' | 'Meal';

export type ScheduleEntry = {
  id: string;
  hourKey: string;
  sortValue: number;
  title: string;
  subtitle?: string;
  type: EntryType;
  passengers?: number;
  ready?: boolean;
  checklistReady?: boolean;
  checklistOverridden?: boolean;
  operationalStatus?: 'planned' | 'proceeding' | 'completed' | 'cancelled';
  booked?: boolean;
  missingCoordinates?: boolean;
  otherComplete?: boolean;
  mealComplete?: boolean;
  transportComplete?: boolean;
  coordinates?: string | null;
  location?: string | null;
  description?: string | null;
  notes?: string | null;
  innhoppReason?: string | null;
  innhoppSequence?: number | null;
  innhoppName?: string | null;
  innhoppElevation?: number | null;
  innhoppCoordinates?: string | null;
  innhoppTakeoffName?: string | null;
  innhoppLandingName?: string | null;
  innhoppAircraftName?: string | null;
  innhoppDistanceByAir?: number | null;
  innhoppAircraftSpeedKmh?: number | null;
  innhoppMinimumLoadDuration?: number | null;
  innhoppAircraftWarning?: string | null;
  innhoppElevationDiff?: number | null;
  innhoppPrimaryName?: string | null;
  innhoppPrimarySize?: string | null;
  innhoppSecondaryName?: string | null;
  innhoppSecondarySize?: string | null;
  innhoppRisk?: string | null;
  innhoppMinimumRequirements?: string | null;
  innhoppRescueBoat?: boolean | null;
  transportRouteOrigin?: string | null;
  transportRouteDestination?: string | null;
  routeDurationLabel?: string;
  routeVehiclesLabel?: string;
  vehicles?: { name: string; driver?: string; passenger_capacity: number }[];
  to?: string;
  scheduledAt?: string | null;
};
